from datetime import datetime, timezone, date
from sqlalchemy import Column, Integer, String, Float, Date, DateTime, ForeignKey, Text, Boolean
from sqlalchemy.orm import relationship
from app.database import Base


class AnalyticsRecord(Base):
    __tablename__ = "analytics_records"

    id = Column(Integer, primary_key=True, index=True)
    hotel_id = Column(Integer, ForeignKey("hotels.id"), nullable=True)
    hotel_name = Column(String(255), nullable=False, index=True)
    property_location = Column(String(255), nullable=True)
    event_id = Column(Integer, ForeignKey("events.id"), nullable=True)
    event_name = Column(String(255), nullable=True, index=True)
    event_type = Column(String(100), default="Regular Hotel Service")
    service_type = Column(String(100), default="Buffet", index=True)
    session = Column(String(100), default="Dinner", index=True)
    record_date = Column(Date, nullable=False, index=True)
    pax = Column(Integer, default=0)
    dish_name = Column(String(255), nullable=False, index=True)
    dish_category = Column(String(100), default="Main Course", index=True)
    food_type = Column(String(100), nullable=True)
    uom = Column(String(50), default="Kg")
    item_cost = Column(Float, default=0.0)
    standard_qty_per_portion = Column(Float, nullable=True)
    conversion_factor = Column(Float, default=1.0)
    estimated_production = Column(Float, default=0.0)
    estimated_production_kg = Column(Float, default=0.0)
    actual_production = Column(Float, default=0.0)
    actual_production_kg = Column(Float, default=0.0)
    over_production = Column(Float, default=0.0)
    over_production_kg = Column(Float, default=0.0)
    pickup_quantity = Column(Float, default=0.0)
    pickup_quantity_kg = Column(Float, default=0.0)
    kitchen_leftover = Column(Float, default=0.0)
    kitchen_leftover_kg = Column(Float, default=0.0)
    location_buffet_return = Column(Float, default=0.0)
    location_buffet_return_kg = Column(Float, default=0.0)
    reuse_quantity = Column(Float, default=0.0)
    reuse_quantity_kg = Column(Float, default=0.0)
    actual_consumption = Column(Float, default=0.0)
    actual_consumption_kg = Column(Float, default=0.0)
    total_leftover = Column(Float, default=0.0)
    total_leftover_kg = Column(Float, default=0.0)
    total_waste = Column(Float, default=0.0)
    total_waste_kg = Column(Float, default=0.0)
    waste_cost = Column(Float, default=0.0)
    waste_percentage = Column(Float, default=0.0)
    waste_per_head_grams = Column(Float, default=0.0)
    consumption_per_head_grams = Column(Float, default=0.0)
    production_per_head_grams = Column(Float, default=0.0)
    reuse_percentage = Column(Float, default=0.0)
    notes = Column(Text, nullable=True)
    data_source = Column(String(100), default="Excel Import")
    ai_confidence = Column(Float, nullable=True)
    source_file = Column(String(255), nullable=True)
    source_sheet = Column(String(100), nullable=True)
    source_row = Column(Integer, nullable=True)
    import_id = Column(String(100), nullable=True, index=True)
    confidence_score = Column(Float, default=1.0)
    reconciliation_variance_kg = Column(Float, default=0.0)
    other_disposition_kg = Column(Float, default=0.0)
    event_subtype = Column(String(100), nullable=True)
    client_name = Column(String(255), nullable=True)
    is_archived = Column(Boolean, default=False, nullable=False, index=True)
    is_verified = Column(Boolean, default=True, nullable=False)
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc), nullable=False)
    updated_at = Column(DateTime, default=lambda: datetime.now(timezone.utc), nullable=False)

